version: "3.7"
services:
  trefu-scraper:
    build: .
    environment:
      START_CODE: 230
      REPORTER_HOST: trefu-be
    networks:
      - origin 
networks:
  origin:
    name: trefu_backend
    external: true